### ISSUE TITLE
[Question] Not quite understand the spring part

### ISSUE THREAD

**Issue by aisensiy** [vorburger/MariaDB4j#261]
After reading the [how-spring](https://github.com/vorburger/MariaDB4j#how-spring) part, I am still confusing about what exactly configuration should I write to switch from a h2 to mariadb4j.

Here is my `application-test.yml` for `h2`:

```
spring:
  datasource:
    url: "jdbc:h2:mem:test;MODE=MySQL"

  flyway:
    locations: "classpath:db/migration,classpath:db/test"
```

By just replacing `"jdbc:h2:mem:test;MODE=MySQL"` to `jdbs:mysql://localhost:3306` I can switch to a real mysql. So...what should I do if I want switch to MariaDB4j in test env?
